version: "3.7"
services:
  app:
    build:
      args:
        user: dungvn
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bm
    container_name: bm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bm

  db:
    image: mysql:5.7
    container_name: bm-db
    restart: unless-stopped
    ports:
      - 3360:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/database:/var/lib/mysql
    networks:
      - bm

  nginx:
    image: nginx:1.17-alpine
    container_name: bm-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bm

networks:
  bm:
    driver: bridge
